apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-management-prod
  namespace: argocd
spec:
  project: employee-management
  source:
    repoURL: https://github.com/dhavalsinhpatil/infra.git
    targetRevision: main
    path: charts/employee-management
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: employee-management-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
