apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: employee-management
  namespace: argocd
spec:
  description: Employee Management Portal
  sourceRepos:
    - https://github.com/dhavalsinhpatil/infra.git
  destinations:
    - namespace: employee-management-dev
      server: https://kubernetes.default.svc
    - namespace: employee-management-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
