apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.namespace }}
data:
  DB_URL: "jdbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.db }}"
  SERVER_PORT: {{ .Values.api.env.serverPort | quote }}
