apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - api/configmap.yaml
  - api/secret.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - ui/deployment.yaml
  - ui/service.yaml
  - ingress.yaml
